<a href="https://colab.research.google.com/github/Probingbug/NN_from_scratch/blob/main/Coding_first_neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
inputs = [1,2,3,2.5]
weights = [0.5,0.25,-0.4,0.6]
bias = 0.2

output = inputs[0]*weights[0]+ inputs[1]*weights[1]+inputs[2]*weights[2] + inputs[3]* weights[3]+bias

print (output)

1.4999999999999998


In [ ]:
#layers of neurons

inputs = [1,2,3,2.5]
weights = [[0.5,0.25,-0.4,0.6], #weights are stored in the manner of weights coming from each input to a single neuron
           [.4,.5,-.3,-0.6], # neuron 2
           [0.7,0.65,0.87,0.98] # neuron 3
          ]

biases=[0.2,0.3,0.4]

outputs = []

for i in range(len(weights)):
    output = inputs[0]*weights[i][0]+ inputs[1]*weights[i][1]+inputs[2]*weights[i][2] + inputs[3]* weights[i][3]+biases[i]
    outputs.append(output)
    print (output)

1.4999999999999998
-0.7
7.46


In [ ]:
# using numpy

import numpy as np
import nnfs # Import nnfs to ensure the modified np.dot is used.

inputs = [1,2,3,2.5]
weights = [[0.5,0.25,-0.4,0.6], #weights are stored in the manner of weights coming from each input to a single neuron
           [.4,.5,-.3,-0.6], # neuron 2
           [0.7,0.65,0.87,0.98] # neuron 3
          ]
biases=[0.2,0.3,0.4]

# Convert lists to numpy arrays
inputs = np.array(inputs)
weights = np.array(weights)
biases = np.array(biases)

output = np.dot(inputs,np.transpose(weights))+ biases
print (output)

[ 1.5  -0.7   7.46]


for batch of inputs

In [ ]:
inputs= [
    [1,2,3,4], #batch one
    [5,6,7,8], #batch 2
    [9,8,7,6]  #batch 3
      ]

weights=[
    [.1,.2,.3,.4],#neuron 1 weights
     [.5,.6,.7,.8], #nueron 2
      [.9,.8,.7,.6] #neuron 3
]

biases=[[0.1,0.2,0.3],
[0.1,0.2,0.3],
[0.1,0.2,0.3]]

# Convert inputs and weights to numpy arrays
inputs = np.array(inputs)
weights = np.array(weights)

output = np.dot(inputs,np.transpose(weights))+ np.array(biases)
print (output)

[[ 3.1  7.2  7.3]
 [ 7.1 17.6 19.3]
 [ 7.1 19.2 23.3]]


**ADDING MULTIPLE LAYERS**

In [ ]:
inputs1 =[[1,2,3,4],[5,6,7,8],[2,3,6,7]]
weights1= [[.1,.2,.3,.4],[.5,.6,.7,.8],[.9,0,.2,.3]]

biases1 = [.2,.3,.5]

weights2 = [
              [0.2,0.4,0.5],
              [.4,-.9,-.5],
              [.6,.7,.8]
            ]
biases2= [.2,.3,.5]

# convert lists into arrays

inputs1 = np.array(inputs1)
weights1 = np.array(weights1)
biases1 = np.array(biases1)
weights2 = np.array(weights2)
biases2 = np.array(biases2)


output1 = np.dot(inputs1, weights1.T) +biases1
output2 = np.dot(output1, weights2.T) +biases2

print (output1)
print (output2)



[[ 3.2  7.3  3.2]
 [ 7.2 17.7  8.8]
 [ 5.6 12.9  5.6]]
[[  5.36  -6.59  10.09]
 [ 13.12 -17.15  24.25]
 [  9.28 -11.87  17.37]]


**CLASSIFYING SPIRAL DATASET USING NN**

In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
  #Layer initialzation
  def __init__(self,n_inputs,n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
    self.biases = np.zeros((1,n_neurons))

  #forward pass

  def forward(self,inputs):
    self.output = np.dot(inputs,self.weights) + self.biases


# create dataset

X,y = spiral_data(samples = 300,classes = 3)

# create the dense layer with 2 input features and 3 output values

dense_1= Layer_Dense(2,3)

#perform forward pass of our training data through this layer

dense_1.forward(X)

#Let's see the output of the first few samples

print(dense_1.output[:5])


[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-5.1206993e-05 -3.3002120e-04  6.2150566e-04]
 [-4.0815637e-04 -7.2520698e-04  1.1652119e-03]
 [-1.3122181e-03 -9.3719346e-04  9.7353902e-04]
 [-1.5902807e-03 -1.3504610e-03  1.6067076e-03]]


In [ ]:
print(dense_1.output.shape)
print(len(dense_1.output))
print(dense_1.output[:5])  # show first 5 entries

(900, 3)
900
[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-5.1206993e-05 -3.3002120e-04  6.2150566e-04]
 [-4.0815637e-04 -7.2520698e-04  1.1652119e-03]
 [-1.3122181e-03 -9.3719346e-04  9.7353902e-04]
 [-1.5902807e-03 -1.3504610e-03  1.6067076e-03]]


In [ ]:
!pip install nnfs

In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
  #Layer initialzation
  def __init__(self,n_inputs,n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
    self.biases = np.zeros((1,n_neurons))

  #forward pass

  def forward(self,inputs):
    self.output = np.dot(inputs,self.weights) + self.biases


# create dataset

X,y = spiral_data(samples = 300,classes = 3)

# create the dense layer with 2 input features and 3 output values

dense_1= Layer_Dense(2,3)

#perform forward pass of our training data through this layer

dense_1.forward(X)

#Let's see the output of the first few samples

print(dense_1.output)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.12069928e-05 -3.30021197e-04  6.21505664e-04]
 [-4.08156367e-04 -7.25206977e-04  1.16521190e-03]
 ...
 [ 1.00714847e-01  1.06049426e-01 -1.42564029e-01]
 [ 4.08301316e-02 -7.35828429e-02  1.74011499e-01]
 [ 1.45113930e-01  7.22821429e-02 -4.53039408e-02]]


In [ ]:
print(len(dense_1.output))

900


**ACTIVATION FUNCTIONS**

In [ ]:
inputs = [
          [1,2,3,4],
          [15,36,57,8],
          [9.3,10.4,1,12]
          ]

#get the unnormalized probability form of output

exp_values = np.exp(inputs-np.max(inputs,axis=1,keepdims=True))

#get actual probability form

probabilities = exp_values/np.sum(exp_values,axis=1,keepdims=True)

print(probabilities)


[[3.20586033e-02 8.71443187e-02 2.36882818e-01 6.43914260e-01]
 [5.74952226e-19 7.58256042e-10 9.99999999e-01 5.24288566e-22]
 [5.29544723e-02 1.59084026e-01 1.31600774e-05 7.87948341e-01]]


In [ ]:
np.sum(probabilities,axis =1 , keepdims=True)

array([[1.],
       [1.],
       [1.]])

**ACTIVATION FUNCTION IN THE FORM OF OOPS**

In [ ]:
class Activation_softmax :
  def forward(self,inputs):
    exp_values = np.exp(inputs- np.max(inputs,axis=1,keepdims = True))
    probablities = exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output= probablities


In [ ]:
class Activation_ReLU:
  def forward(self,inputs):
    self.output = np.maximum(0,inputs)

**LET'S MAKE IT WORK ON A DATASET**

In [ ]:
#create a dataset
X,y = spiral_data(samples = 100, classes = 3)

print(len(X))

# Create a dense layer with two input features and 3 output values
Dense1 = Layer_Dense(2,3)
Dense1.forward(X)

# ReLU activation function
activation1 = Activation_ReLU()
activation1.forward(Dense1.output)

print(activation1.output.shape)

# Create second dense layer with 3 inputs and 3 outputs
Dense2  = Layer_Dense(3,2)
Dense2.forward(activation1.output)

Activation2= Activation_softmax()
Activation2.forward(Dense2.output)

print(Activation2.output.shape)

# make a forwarf pass of our training data through this layer


# make forward pass through activation function
# it takes output from the neurons and pass it through the ReLU Activation function


##similarly for second layer



print(Activation2.output[:5])




300
(300, 3)
(300, 2)
[[0.5        0.5       ]
 [0.49998558 0.5000144 ]
 [0.49997503 0.500025  ]
 [0.49996287 0.50003713]
 [0.49993548 0.50006455]]


In [ ]:
print(len(Activation2.output))

300


In [ ]:
len(Activation2.output)  # ➜ 300
Activation2.output.shape

(300, 2)

**NOW LET'S FIND THE LOSS OF THIS NETWORK**

First of all I store the maximum probability from ech batch of input.

In [ ]:
class_target = np.max(Activation2.output,axis=1,keepdims=True)
print(class_target[:5])

[[0.5       ]
 [0.5000144 ]
 [0.500025  ]
 [0.50003713]
 [0.50006455]]


Now, pass it to the formula of categorical cross entropy loss. -(log(p))

In [ ]:
c=-np.log(class_target)
print(c[:5])

[[0.6931472 ]
 [0.69311833]
 [0.69309723]
 [0.6930729 ]
 [0.6930181 ]]


In [ ]:
np.mean(c)

np.float32(0.6923797)

there is one more method of doing the same thing.
Take the one hot encoding for each batch then take the element wise multiplication of that onehot encoding with the actual probability matrix.
Then it is going to give you the only one element which is having highest probability as one hot encoing is one for the highest value and zero for others.

then simply pass it through the sum function then -np.log(probability) value..
then take the mean of that value . mean error will be there as the result.