<a href="https://colab.research.google.com/github/Probingbug/NN_from_scratch/blob/main/Multilayer_backpropogation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

inputs = [1,2,3,4]
biases = [0.1,0.2,0.3]
weights=[[0.1,0.2,0.3,0.4],[0.9,0.8,0.7,0.6],[0.5,0.7,0.6,0.3]]

learning_rate = 0.001

#activation function

def relu(x):
  return np.maximum(0,x)

def relu_derivative(x):
   return np.where(x>0,1,0)

# training loop

for iteration in range ( 90):


  # forward pass

  z= np.dot(weights,inputs)+biases
  a = relu(z)
  y=np.sum(a,axis=0)

  #calculate loss
  loss = y**2

  #backward pass


  # Scalar to vector gradients
  dl_dy = 2 * y                            # scalar
  dy_da = np.ones_like(a)                 # shape: (3,)
  dl_da = dl_dy * dy_da                   # shape: (3,)
  da_dz = relu_derivative(z)              # shape: (3,)
  dl_dz = dl_da * da_dz                   # shape: (3,)

  # Now, compute outer product to match shape of weights (3, 4)
  dl_dw = np.outer(dl_dz, inputs)         # shape: (3, 4)
  dl_db = dl_dz     # shape: (3,)

  #updation
  weights -= learning_rate * dl_dw
  biases -= learning_rate * dl_db


  #print the loss

  if iteration % 10 == 0:
    print(f"iteration {iteration+1}: loss={loss}")

#final loss,biases and weights

print(f"final loss: {loss}")
print(f"final weights: {weights}")
print(f"final biases: {biases}")






iteration 1: loss=240.25
iteration 11: loss=8.827021031924428
iteration 21: loss=1.630381905604496
iteration 31: loss=0.4532586640113987
iteration 41: loss=0.12600938209334828
iteration 51: loss=0.035031573881063344
iteration 61: loss=0.009739045999569202
iteration 71: loss=0.002707529421993686
iteration 81: loss=0.0007527139281697362
final loss: 0.0002378378898668657
final weights: [[-0.00710446 -0.01420892 -0.02131338 -0.02841784]
 [ 0.66820858  0.33641715  0.00462573 -0.3271657 ]
 [ 0.33221274  0.36442549  0.09663823 -0.37114903]]
final biases: [-0.00710446 -0.03179142  0.13221274]


**softmax and cross entropy loss functions**

In [ ]:
def activation_softmax():
  def forward(self,inputs):
    exp_values = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
    probabilities = exp_values / np.sum(exp_values,axis=1,keepdims=True)

def loss_categoricalCrossentropy():
  def calculate(self,output,y):
    samples = len(output)
    output_clipped = np.clip(output,1e-7,1-1e-7)

**Backward pass through softmax function.**
combined softmax activation and cross-entropy loss for faster backward step

In [ ]:
# softmax classifier - combined softmax activation
# and cross- entropy loss for faster backward step

class activation_softmax_loss_categoricalCrossentropy():
  #Creater activation and loss function objects

  def __init__(self):
    self.activation = activation_softmax()
    self.loss = loss_categoricalCrossentropy()

  # forward pass

  def forward(self, inputs , y_true ):
    # output layer's activation function

    self.activation.forward(inputs)
    #set the inputs
    self.output = self.activation.output
    #calculate and return loss value
    return self.loss.calculate(self.output,y_true)


  #backward pass

  def backward(self,dvalues,y_true):
    #numbers of samples
    samples = len(dvalues)
    #if labels are one-hot encoded,
    #turn them into discrete values
    if len(y_true.shape) == 2:
      y_true = np.argmax(y_true,axis = 1) # when class targets are one hot encoded
    #copy so we can modify safely
    self.dinputs = dvalues.copy()
    #calculate gradients
    self.dinputs[range(samples),y_true] -=1. #only those block will be modify those are with y_true values
    #normalize gradient
    self.dinputs = self.dinputs / samples

In [ ]:
softmax_outputs = np.array ([[0.7,0.1,0.2],
                             [0.1,0.5,0.4],
                             [0.02,0.9,0.08]])

class_targets = np.array([0,1,1])

softmax_loss = activation_softmax_loss_categoricalCrossentropy()
softmax_loss.backward(softmax_outputs,class_targets)
dvalues = softmax_loss.dinputs
print("gradients : combined loss and activation :")
print(dvalues)


gradients : combined loss and activation :
[[-0.1         0.03333333  0.06666667]
 [ 0.03333333 -0.16666667  0.13333333]
 [ 0.00666667 -0.03333333  0.02666667]]
